### ISSUE TITLE
希望可以换行

### ISSUE THREAD

**Issue by itsdrchen** [wong2/chathub#5]
Enter键为发送，文字输入时无法换行，希望能增加一个换行功能，开发者辛苦了!

**Comment by wong2** [comment]
shift+enter 换行

**Comment by wong2** [comment]
和微信一样的

**Comment by PlayerYK** [comment]
> 和微信一样的

微信 Ctrl+Enter 也可以换行，可以考虑加一下么。
（我之前都不知道微信可以用Shift+Enter换行，所以也不知道ChatHub可以换行-_-!!!）
